# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1182, 744)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.directorybox = QtGui.QLineEdit(self.centralwidget)
        self.directorybox.setReadOnly(True)
        self.directorybox.setObjectName(_fromUtf8("directorybox"))
        self.verticalLayout.addWidget(self.directorybox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.browsebutton = QtGui.QPushButton(self.centralwidget)
        self.browsebutton.setObjectName(_fromUtf8("browsebutton"))
        self.horizontalLayout.addWidget(self.browsebutton)
        self.clearbutton = QtGui.QPushButton(self.centralwidget)
        self.clearbutton.setObjectName(_fromUtf8("clearbutton"))
        self.horizontalLayout.addWidget(self.clearbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.scriptlist = QtGui.QListWidget(self.centralwidget)
        self.scriptlist.setObjectName(_fromUtf8("scriptlist"))
        self.verticalLayout.addWidget(self.scriptlist)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 1, 1, 1)
        self.commentcheck = QtGui.QCheckBox(self.centralwidget)
        self.commentcheck.setObjectName(_fromUtf8("commentcheck"))
        self.gridLayout_2.addWidget(self.commentcheck, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 1, 1, 1)
        self.functioncheck = QtGui.QCheckBox(self.centralwidget)
        self.functioncheck.setObjectName(_fromUtf8("functioncheck"))
        self.gridLayout_2.addWidget(self.functioncheck, 1, 0, 1, 1)
        self.comment_freq = QtGui.QLineEdit(self.centralwidget)
        self.comment_freq.setObjectName(_fromUtf8("comment_freq"))
        self.gridLayout_2.addWidget(self.comment_freq, 0, 2, 1, 1)
        self.timeout_box = QtGui.QLineEdit(self.centralwidget)
        self.timeout_box.setObjectName(_fromUtf8("timeout_box"))
        self.gridLayout_2.addWidget(self.timeout_box, 0, 4, 1, 1)
        self.avg_func_len = QtGui.QLineEdit(self.centralwidget)
        self.avg_func_len.setBaseSize(QtCore.QSize(0, 0))
        self.avg_func_len.setObjectName(_fromUtf8("avg_func_len"))
        self.gridLayout_2.addWidget(self.avg_func_len, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 3, 1, 1)
        self.define_inout = QtGui.QPushButton(self.centralwidget)
        self.define_inout.setObjectName(_fromUtf8("define_inout"))
        self.gridLayout_2.addWidget(self.define_inout, 1, 4, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 1)
        self.gridLayout_2.setColumnMinimumWidth(2, 3)
        self.gridLayout_2.setColumnMinimumWidth(3, 1)
        self.gridLayout_2.setColumnMinimumWidth(4, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.StatusBox = QtGui.QTextBrowser(self.centralwidget)
        self.StatusBox.setObjectName(_fromUtf8("StatusBox"))
        self.verticalLayout_2.addWidget(self.StatusBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.errornum = QtGui.QLineEdit(self.centralwidget)
        self.errornum.setReadOnly(True)
        self.errornum.setObjectName(_fromUtf8("errornum"))
        self.gridLayout.addWidget(self.errornum, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.errorweight = QtGui.QLineEdit(self.centralwidget)
        self.errorweight.setReadOnly(False)
        self.errorweight.setObjectName(_fromUtf8("errorweight"))
        self.errorweight.setText("0")
        self.gridLayout.addWidget(self.errorweight, 3, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.incorrectweight = QtGui.QLineEdit(self.centralwidget)
        self.incorrectweight.setReadOnly(False)
        self.incorrectweight.setObjectName(_fromUtf8("incorrectweight"))
        self.incorrectweight.setText("5")
        self.gridLayout.addWidget(self.incorrectweight, 2, 4, 1, 1)
        self.correctweight = QtGui.QLineEdit(self.centralwidget)
        self.correctweight.setReadOnly(False)
        self.correctweight.setObjectName(_fromUtf8("correctweight"))
        self.correctweight.setText("10")
        self.gridLayout.addWidget(self.correctweight, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.linenumbers = QtGui.QLineEdit(self.centralwidget)
        self.linenumbers.setReadOnly(True)
        self.linenumbers.setObjectName(_fromUtf8("linenumbers"))
        self.gridLayout.addWidget(self.linenumbers, 1, 1, 1, 1)
        self.functionnumbers = QtGui.QLineEdit(self.centralwidget)
        self.functionnumbers.setReadOnly(True)
        self.functionnumbers.setObjectName(_fromUtf8("functionnumbers"))
        self.gridLayout.addWidget(self.functionnumbers, 2, 1, 1, 1)
        self.commentnumbers = QtGui.QLineEdit(self.centralwidget)
        self.commentnumbers.setReadOnly(True)
        self.commentnumbers.setObjectName(_fromUtf8("commentnumbers"))
        self.gridLayout.addWidget(self.commentnumbers, 3, 1, 1, 1)
        self.incorrectnum = QtGui.QLineEdit(self.centralwidget)
        self.incorrectnum.setReadOnly(True)
        self.incorrectnum.setObjectName(_fromUtf8("incorrectnum"))
        self.gridLayout.addWidget(self.incorrectnum, 2, 3, 1, 1)
        self.correctnum = QtGui.QLineEdit(self.centralwidget)
        self.correctnum.setReadOnly(True)
        self.correctnum.setObjectName(_fromUtf8("correctnum"))
        self.gridLayout.addWidget(self.correctnum, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.IO_score = QtGui.QLineEdit(self.centralwidget)
        self.IO_score.setText(_fromUtf8(""))
        self.IO_score.setObjectName(_fromUtf8("IO_score"))
        self.gridLayout_3.addWidget(self.IO_score, 2, 1, 1, 1)
        self.Function_score = QtGui.QLineEdit(self.centralwidget)
        self.Function_score.setText(_fromUtf8(""))
        self.Function_score.setObjectName(_fromUtf8("Function_score"))
        self.gridLayout_3.addWidget(self.Function_score, 0, 1, 1, 1)
        self.comment_score = QtGui.QLineEdit(self.centralwidget)
        self.comment_score.setObjectName(_fromUtf8("comment_score"))
        self.comment_score.setText(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comment_score, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.Total_score = QtGui.QLineEdit(self.centralwidget)
        self.Total_score.setObjectName(_fromUtf8("Total_score"))
        self.gridLayout_3.addWidget(self.Total_score, 3, 1, 1, 1)
        self.exportbutton = QtGui.QPushButton(self.centralwidget)
        self.exportbutton.setObjectName(_fromUtf8("exportbutton"))
        self.gridLayout_3.addWidget(self.exportbutton, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Autograder", None))
        self.label.setText(_translate("MainWindow", "Directory:", None))
        self.browsebutton.setText(_translate("MainWindow", "Browse", None))
        self.clearbutton.setText(_translate("MainWindow", "Clear", None))
        self.label_2.setText(_translate("MainWindow", "Recognized Scripts:", None))
        self.label_15.setText(_translate("MainWindow", "Comment Frequency", None))
        self.commentcheck.setText(_translate("MainWindow", "Check for Comments", None))
        self.label_16.setText(_translate("MainWindow", "Avg. Function Length", None))
        self.functioncheck.setText(_translate("MainWindow", "Check for functions", None))
        self.comment_freq.setText(_translate("MainWindow", "10", None))
        self.timeout_box.setText(_translate("MainWindow", "10", None))
        self.avg_func_len.setText(_translate("MainWindow", "20", None))
        self.label_14.setText(_translate("MainWindow", "Timeout (seconds):", None))
        self.define_inout.setText(_translate("MainWindow", "Define Input/Output Cases", None))
        self.label_5.setText(_translate("MainWindow", "Status:", None))
        self.label_9.setText(_translate("MainWindow", "Weight", None))
        self.label_10.setText(_translate("MainWindow", "Number", None))
        self.label_11.setText(_translate("MainWindow", "Lines", None))
        self.label_12.setText(_translate("MainWindow", "Comments", None))
        self.label_13.setText(_translate("MainWindow", "Functions", None))
        self.label_6.setText(_translate("MainWindow", "Correct Answers", None))
        self.label_7.setText(_translate("MainWindow", "Incorrect Answers", None))
        self.label_8.setText(_translate("MainWindow", "Errors", None))
        self.label_4.setText(_translate("MainWindow", "Function Score", None))
        self.label_17.setText(_translate("MainWindow", "Total Score", None))
        self.label_18.setText(_translate("MainWindow", "Input Output Score", None))
        self.label_3.setText(_translate("MainWindow", "Comment Score", None))
        self.exportbutton.setText(_translate("MainWindow", "Export", None))

